In [1]:
from classes import *
import random as rnd

In [2]:
a = QBM(1, 1, "Test")
a.path = "../TEST/"
a.read_data()
a.read_coef("418")
a.t_step = 1000

right = [0] * a.outlen
in3 = [0] * a.outlen
total3 = [0] * a.outlen
for i in range(1000):
    a.read_image(i)
    a.analyze_answer()
    if a.expected == a.top[0]:
        right[a.expected] += 1
    if a.expected in a.top:
        in3[a.expected] += 1
    total3[a.expected] += 1
    print("Got", a.top, "expected", a.expected)
print(right, "right out of ", total3," ,", in3, "in top 3 out of", total3)

In [3]:
a.find_answer(100)

[0.19470341 0.19653819 0.19851194 0.20926008 0.20098638]
[0.20009626 0.19938976 0.195688   0.20690696 0.19791903]
[0.19629789 0.19808573 0.20127713 0.20512752 0.19921172]
[0.19611656 0.19485356 0.20150891 0.20824149 0.19927947]
[0.19696884 0.20196946 0.19934535 0.20070453 0.20101182]
[0.20321375 0.20293513 0.19598497 0.20102375 0.19684241]
[0.19647476 0.1947147  0.203123   0.20425514 0.2014324 ]
[0.19470341 0.19653819 0.19851194 0.20926008 0.20098638]
[0.19470341 0.19653819 0.19851194 0.20926008 0.20098638]
[0.19969384 0.19674239 0.20122169 0.20160639 0.2007357 ]
[0.19082365 0.20180763 0.20193837 0.20672854 0.1987018 ]
[0.20149496 0.19686783 0.2002556  0.19495748 0.20642413]
[0.19969384 0.19674239 0.20122169 0.20160639 0.2007357 ]
[0.19611656 0.19485356 0.20150891 0.20824149 0.19927947]
[0.19248217 0.19936442 0.2027394  0.20595615 0.19945785]
[0.19969384 0.19674239 0.20122169 0.20160639 0.2007357 ]
[0.20390659 0.20337391 0.19347968 0.20193345 0.19730636]
[0.19969384 0.19674239 0.201221

array([[0.19470341, 0.19653819, 0.19851194, 0.20926008, 0.20098638],
       [0.20009626, 0.19938976, 0.195688  , 0.20690696, 0.19791903],
       [0.19629789, 0.19808573, 0.20127713, 0.20512752, 0.19921172],
       [0.19611656, 0.19485356, 0.20150891, 0.20824149, 0.19927947],
       [0.19696884, 0.20196946, 0.19934535, 0.20070453, 0.20101182],
       [0.20321375, 0.20293513, 0.19598497, 0.20102375, 0.19684241],
       [0.19647476, 0.1947147 , 0.203123  , 0.20425514, 0.2014324 ],
       [0.19470341, 0.19653819, 0.19851194, 0.20926008, 0.20098638],
       [0.19470341, 0.19653819, 0.19851194, 0.20926008, 0.20098638],
       [0.19969384, 0.19674239, 0.20122169, 0.20160639, 0.2007357 ],
       [0.19082365, 0.20180763, 0.20193837, 0.20672854, 0.1987018 ],
       [0.20149496, 0.19686783, 0.2002556 , 0.19495748, 0.20642413],
       [0.19969384, 0.19674239, 0.20122169, 0.20160639, 0.2007357 ],
       [0.19611656, 0.19485356, 0.20150891, 0.20824149, 0.19927947],
       [0.19248217, 0.19936442, 0.

In [4]:
a.coef

array([[ 7.28024189e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -8.85945253e-03,  1.10348557e-02,  1.49333175e-02,
         5.70510940e-03,  8.92976418e-03,  3.25827143e-03,
         1.02159969e-02,  4.60012150e-03,  7.51274816e-03],
       [ 0.00000000e+00, -9.25332269e-02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.43602339e-02, -6.77474976e-03,  1.17822125e-03,
        -9.02749148e-03, -1.06989996e-02, -4.42239167e-03,
         2.63095739e-03,  5.97845159e-03, -5.46744354e-03],
       [ 0.00000000e+00,  0.00000000e+00,  5.14845013e

In [5]:
np.arange(6).reshape((2, 3))[0][2]

2

In [6]:
a.outlen

5

In [7]:
e ** -3

0.04978706836786395