In [1]:
from classes import *

def test(a, b):
    qbm = QBM(a, b, 1)
    qbm.read_images()
    return qbm
a = test(1, 2)

In [2]:
a.coef = np.zeros((3, 3), dtype = np.int_)
a.coef[0] = [0, 1, -1]
a.coef[1] = [0, 0, 0]
a.coef[2] = [0, 0, 0]
a.coef

array([[ 0,  1, -1],
       [ 0,  0,  0],
       [ 0,  0,  0]])

In [3]:
l = 100
a.chosen_images = np.ones((l, 2), dtype = np.int_)
for i in range(l // 2):
    a.chosen_images[i] = - a.chosen_images[i]
for i in range(l):
    a.chosen_images[i][1] = - a.chosen_images[i][0]
a.mean_single = [0 ,0]

In [4]:
a.double_unfixed = np.zeros((3,3), dtype = np.float_)
a.double_unfixed[0] = [0, 1, -1]

In [5]:
a.calc_double_fixed()

Image:  0


In [6]:
v = a.calc_sigma_v([1, -1])
k = a.calc_sigma_v([-1, 1])

In [7]:
print(v)
print(k)

[0.96402758 0.         0.        ]
[-0.96402758  0.          0.        ]


In [8]:
a.calc_double_fixed()
a.single_fixed

Image:  0


array([4.4408921e-18, 0.0000000e+00, 0.0000000e+00])

In [9]:
a.single_fixed = np.zeros(a.vislen + a.hidlen, dtype = np.float_)
for v in a.chosen_images:
    a.single_fixed += a.calc_sigma_v(v)
a.single

[-0.96402758  0.          0.        ]
[-1.92805516  0.          0.        ]
[-2.89208274  0.          0.        ]
[-3.85611032  0.          0.        ]
[-4.8201379  0.         0.       ]
[-5.78416548  0.          0.        ]
[-6.74819306  0.          0.        ]
[-7.71222064  0.          0.        ]
[-8.67624822  0.          0.        ]
[-9.6402758  0.         0.       ]
[-10.60430338   0.           0.        ]
[-11.56833096   0.           0.        ]
[-12.53235854   0.           0.        ]
[-13.49638612   0.           0.        ]
[-14.4604137   0.          0.       ]
[-15.42444128   0.           0.        ]
[-16.38846886   0.           0.        ]
[-17.35249644   0.           0.        ]
[-18.31652402   0.           0.        ]
[-19.2805516   0.          0.       ]
[-20.24457918   0.           0.        ]
[-21.20860676   0.           0.        ]
[-22.17263434   0.           0.        ]
[-23.13666192   0.           0.        ]
[-24.1006895   0.          0.       ]
[-25.06471708   0.  

In [10]:
a.double_unfixed

array([[ 0.,  1., -1.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])